instaklooni/urls.py
from django.urls import path,include,reverse_lazy
from django.contrib import admin
from django.contrib.auth import views
from django_registration.backends.one_step.views import RegistrationView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('klooni.urls')),
    path('accounts/register/',RegistrationView.as_view(success_url='/accounts/login/')),
    path('accounts/',include('django_registration.backends.one_step.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('logout/',views.LogoutView.as_view(),{'next_page':'/'}),
]

klooni/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

urlpatterns = [
    path('',views.landing,name='klooniLandingPage'),
    path('home/',views.home,name='klooniHome'),
    path('search/', views.search_results,name='search_results'),
    path('profile/',views.profilePage,name='klooniProfile'),
    path('like/<int:image_id>',views.likes,name='likes'),
    path('comment/<int:image_id>',views.comments,name='comments'),
    path('upload/',views.uploadPic,name='klooniFeed'),
    path('update-profile/',views.updateProfile,name='editProfile'),
    
   ]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

klooni/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime as dt
from pyuploadcare.dj.models import ImageField
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

#Profile model
class Profile(models.Model):
    prof_pic = ImageField(blank=True, manual_crop="")
    bio = models.CharField(max_length = 200)
    user = models.OneToOneField('auth.User',on_delete=models.CASCADE, default=None)
    
    def save_profile(self):
        self.save()
            
    def update_profile(self):
        prof=Profile.objects.filter(id=Profile.id).update()
        
    def delete_image(self):
        prof=Profile.objects.filter(id=Profile.id).delete()
        
    
    @classmethod
    def profile(cls):
        profile = cls.objects.filter(id=Profile.id)
        return profile
    
    def __str__(self):
        return str(self.user)
    
@receiver(post_save,sender=User)
def create_profile(sender, instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)
        
@receiver(post_save,sender=User)
def save_profile(sender, instance,**kwargs):
    instance.profile.save()

#Image Model
class Image(models.Model):
    image = ImageField(manual_crop="")
    name = models.CharField(max_length =70)
    caption = models.CharField(max_length =700)
    post_date = models.DateTimeField(auto_now_add=True)
    profile = models.ForeignKey(User, on_delete=models.CASCADE)
    user = models.ForeignKey(Profile, on_delete=models.CASCADE, default=None)

    
    def save_image(self):
        self.save()
            
    def update_image(self):
        img=Image.objects.filter(id=Image.id).update()
        
    def update_caption(self):
        img=Image.objects.filter(id=Image.id).update()     
        
    def delete_image(self):
        # img = get_object_or_404(Image,pk=Image.id)
        img=Image.objects.filter(id=Image.id).delete()
   
    class Meta:
        ordering = ['post_date']
    
    @classmethod
    def images(cls):
        images = cls.objects.filter(id=Image.id)
        return images
    
    
    @classmethod
    def search_by_username(cls,username):
        fetch_user= User.objects.get(username=username)
        foundUser = cls.objects.filter(profile=fetch_user)
        return foundUser
    
    @classmethod
    def filter_by_user_id(cls):
        photos = cls.objects.filter(id=user.user_id)
        return photos
    
    def __str__(self):
        return str(self.name)
    
class Like(models.Model):
    likes = models.IntegerField(blank=True)
    image = models.ForeignKey(Image, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User,on_delete=models.CASCADE)

    def save_like(self):
        self.save()
        
    def __str__(self):
        return str(self.likes)

class Comment(models.Model):
    comments = models.CharField(max_length =200, blank=True)
    image = models.ForeignKey(Image, on_delete=models.CASCADE, default=None)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    
    def save_comment(self):
        self.save()
        
    @classmethod
    def get_comments(cls,id):
        comments = cls.objects.filter(image__id=id)
        
        return comments
        
    def __str__(self):
        return str(self.comments)

klooni/forms.py
from django import forms
from .models import *
from pyuploadcare.dj.forms import ImageField

class LikesForm(forms.Form):
    class Meta:
        model = Image
        exclude = '__all__'

class CommentsForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['image', 'user']
        
class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields=['prof_pic','bio']
        
        
class UploadPicForm(forms.ModelForm):
    class Meta:
        model = Image
        # imagefile = Image.image=('Select a file')
        fields=('image','name','caption',)
        # exclude = ['profile','post_date','user']

klooni/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import login, views, forms
from django.contrib.auth.decorators import login_required
from .models import *
from django.contrib.auth.models import User
from .forms import LikesForm, CommentsForm, UpdateProfileForm, UploadPicForm
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse,Http404,HttpResponseRedirect




#landing page
def landing(request):
    form = forms.AuthenticationForm
    return render(request, 'landing_page.html', locals())

#home page
@login_required(login_url='/accounts/login')
def home(request):
    likesForm = LikesForm
    commentForm = CommentsForm
    images = Image.objects.all()
    user = request.user.get_username()
    profile = Profile.objects.all()
    likes = Like.objects.all()
    # numberOfLikes = len(likes)
    # comments = Comment.get_comments(id)
    # comments = Comment.objects.all()
    # numberOfComments=len(comments)
    # commentsPerImage = Comment.objects.filter(image_id=images.id).all()
    
    
    return render(request,'klooni_pages/home.html', locals())

def likes(request,image_id):
    likesForm = LikesForm()
    # if request.method == 'POST':
    #     likesForm = LikesForm(request.POST)
    #     if likesForm.is_valid():
    #         form = likesForm.save(commit=False)
            # form.user=request.user
            # form.image= get_object_or_404(Image,pk=image_id)
            # form.like= 1
            # form.save()
    #    CRUD     
    obj1=Like.objects.create(user=request.user,image=get_object_or_404(Image,pk=image_id),likes=1)
    obj1.save()
    print(obj1)
    return redirect('klooniHome')

def comments(request,image_id):
    commentsForm = CommentsForm()
    if request.method == 'POST':
        commentsForm = CommentsForm(request.POST)
        if commentsForm.is_valid():
            form = commentsForm.save(commit=False)
            form.user=request.user
            form.image = get_object_or_404(Image,pk=image_id)
            form.save()
  
    return redirect('klooniHome')

#search feature
@login_required(login_url='/accounts/login')
def search_results(request):
    likesForm = LikesForm
    commentForm = CommentsForm
    images = Image.objects.all()
    user = request.user.get_username()
    current_user = request.user
    photos = Image.objects.filter(profile=current_user.id)
    profile = Profile.objects.all()
    likes = Like.objects.all()
    
      
    try:
        user = User.objects.get(id =request.user.id)
    except ObjectDoesNotExist:
        raise Http404()
    message = 'based on your search term'
    return render(request, 'klooni_pages/search.html',locals())
    
    
    if 'username' in request.GET and request.GET["username"]:
        form = forms.AuthenticationForm
        images = Image.objects.all()
        user = request.user.get_username()
        profile = Profile.objects.all()
        search_term = request.GET.get("username")
        searched_users = Image.search_by_username(search_term)
        message = f"{search_term}"
        # print(User.objects.get(username=search_term))
        photos = Image.objects.filter(profile=User.objects.get(username=search_term))


        return render(request, 'klooni_pages/search.html',locals())

    else:
        message = "You haven't searched for any term"
        return render(request, 'klooni_pages/search.html',locals())


#profile page
@login_required(login_url='/accounts/login')
def profilePage(request):
    likesForm = LikesForm
    commentForm = CommentsForm
    images = Image.objects.all()
    user = request.user.get_username()
    current_user = request.user
    photos = Image.objects.filter(profile=current_user.id)
    profile = Profile.objects.all()
    likes = Like.objects.all()
 
    
    return render(request,'klooni_pages/profile.html', locals())




#update current user profile
@login_required(login_url='/accounts/login')
def updateProfile(request):
    current_user = request.user
    my_prof = Profile.objects.get(user=current_user.id)
    updateForm = UpdateProfileForm(instance=request.user)
 
    if request.method == 'POST':
        updateForm = UpdateProfileForm(request.POST,request.FILES,instance=request.user.profile)

        if updateForm.is_valid():
            updateForm.save()
            
            
        return redirect('klooniProfile')
    else:
        updateForm = UpdateProfileForm(instance=request.user.profile)

    return render(request,'klooni_pages/update_profile.html', locals())



#upload feed/pic/video page
@login_required(login_url='/accounts/login')
def uploadPic(request):
    current_user = request.user
    # my_prof = Profile.objects.get(id=current_user.id)
    uploadForm = UploadPicForm()
    print(uploadForm)
    # uploadForm = UploadPicForm(request.POST or None,request.FILES or None)
 

    if request.method == 'POST':
        uploadForm = UploadPicForm(request.POST,request.FILES)
        # profile = request.user.username
        # uploadForm = UploadPicForm(request.POST or None,request.FILES or None)
        user = request.user.id

        if uploadForm.is_valid():
            upload = uploadForm.save(commit=False)
            upload.user = request.user.profile
            upload.profile = current_user
            upload.save()
            
        
            
        return redirect('klooniProfile')
    else:
        # uploadForm = UploadPicForm(request.POST or None,request.FILES or None)
            uploadForm = UploadPicForm()

    return render(request,'klooni_pages/upload_pic.html', locals())

klooni/templates/klooni_pages/base.html
{% load bootstrap4 %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">

  {% if title %}
  <title> insta-klooni - {{title}}</title>
  {% else %}
    <title> insta-klooni </title>
  {% endif %}

{% block styles %}
{% bootstrap_css %}
<link href="https://fonts.googleapis.com/css?family=Cookie|Courgette|Lobster|News+Cycle&display=swap" rel="stylesheet">
<link href='https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css'>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel='stylesheet' href='{% static 'css/baseklooni.css'%}'>
{% endblock %}
{{updateForm.media}}

{{uploadForm.media}}
</head>
<body>
    {% block content %} 

    {% include 'navbar.html' %} {% comment %} for some reason, this didn't work, included it in the pages where relevant {% endcomment %}
    
    {% endblock %}

{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% bootstrap_javascript %}
{% endblock %}    

</body>
</html>

klooni/templates/klooni_pages/home.html
{% extends 'klooni_pages/base.html'%}
{% load bootstrap4 %}

{% block content %}


<div class='container'>
    {% include 'navbar.html' %}
<hr>

<div class='row justify-content-center top-buffer'>
{% for item in images %}

<div class='col-xs-7 col-sm-7 col-md-7 col-lg-7 d-block top-buffer'> 


<div class='d-inline-flex'>
<div class="userAvatar mr-2"> <img class='img-thumbnail' src="{{item.user.prof_pic.cdn_url}}" alt='userAvatar'></div>

<div class='text-center align-self-center'> <strong> {{ item.user.user.username}} </strong> </div>
</div>


<div class='justify-content-center'>
<img class='img-responsive imagePost' src="{{item.image.cdn_url}}" alt='Image' data-toggle='modal' data-target="#{{item.id}}">

<!-- likes and comments -->
<p>{{ item.like_set.all|length }} <i class="fa fa-heart-o"></i>  
{{ item.comment_set.all|length }} <i class="fa fa-commenting-o"></i></p>



<!-- The Modal -->

<div class="modal fade" id="{{item.id}}">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">

      <!-- Modal Header -->
      <div class="modal-header">
        <h4 class="modal-title"> {{item.name}} </h4>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>

      <!-- Modal body -->
      <div class="modal-body">
       <div class='d-inline-flex'>

<div class="userAvatar mr-2"> <img class='img-thumbnail' src="{{item.user.prof_pic.cdn_url}}" alt='userAvatar'></div>

<div class='text-center align-self-center'> <strong> {{ item.user.user.username}} </strong> </div>
</div>

<div class='d-flex justify-content-center'>
<img class='img-responsive imagePost' src="{{ item.image.cdn_url }}" alt='image'>
</div>

<p> {{item.name}} </p>
<p> {{ item.caption }} </p>
<p>{{item.like_set.all|length }} <i class="fa fa-heart-o"></i> 
{{ item.comment_set.all|length }} <i class="fa fa-commenting-o"></i></p>

      </div>

      <!-- Modal footer -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>

    </div>
  </div>
</div>

<!-- end modal -->



<!-- list of posted comments -->

{{ item.comment_set.all|length }} Comment(s)

<ul style="list-style-type: none">
{% for comment in item.comment_set.all %}
<li> {{comment.comments}} </li>
{% endfor %}
</ul>

<!-- end of list of comments -->
<div>

    <form  action="{% url 'comments' image_id=item.id %}" method="post">

    {% csrf_token %}

    {% bootstrap_form commentForm layout='inline' %}

    <div class="form-group">

 

    <input type="submit" class="btn btn-primary btn-sm my-2" value="Post Comment">
    </div>
   </form>
</div>

<hr>
</div>

</div>
{% endfor %}

</div>
</div>


{% endblock %}

klooni/templates/klooni_pages/profile.html
{% extends 'klooni_pages/base.html'%}
{% load bootstrap4 %}

{% block content %}


<div class='container'>
    {% include 'navbar.html' %}
<hr>

<div class='row justify-content-center top-buffer'>


    <div class='col-xs-7 col-sm-7 col-md-7 col-lg-7 d-block top-buffer'> 

{% comment %} {% for photo in photos %} {% endcomment %}

    <div class='d-inline-flex'>
    <div class="userAvatar mr-2"> <img class='img-thumbnail' src="{{request.user.profile.prof_pic.cdn_url}}" alt='userAvatar'></div>

    <div class='text-center mr-2 align-self-center'> <strong> {{ request.user.profile.username}} </strong> </div>
    </div>
    <hr>
    <div class='text-center align-self-center'> <p> Email:  {{ request.user.email }} </p></div>

    <div class='text-center align-self-center'> <p> Bio:  {{ request.user.profile.bio}} </p>  
    </div>

    <div class='text-center align-self-center'> <p> <a href={% url 'editProfile' %}> Edit Bio </a> </p>  
    </div>  

    <hr>
{% comment %} {% endfor  %} {% endcomment %}




    {% for photo in photos %}

    <h5> My Posts... </h5>
    {% comment %} pics posted by current_user {% endcomment %}
    <div class='d-flex justify-content-center'>
    <img class='img-responsive imagePost' src="{{photo.image.cdn_url}}" alt='image'>
    </div>

    <p> {{photo.name}} </p>
    <p> {{ photo.caption }} </p>

    <p>
    {{photo.like_set.all|length}}  <i class="fa fa-heart-o"></i>   {{photo.comment_set.all|length}} <i class="fa fa-commenting-o"></i> </p>
    <hr>
    {% endfor %}

    </div>




<!-- if no posts yet then -->

    {% if photos %}

    {% else %}


 <div class='d-flex col-xs-7 col-sm-7 col-md-7 col-lg-7 text-center'>

<div class='userAvatar float-left'><img class='img-thumbnail' src="{{request.user.profile.prof_pic.cdn_url}}" alt='userAvatar'></div>

<div class='align-self-center mx-auto'> <strong> {{ request.user.username}} </strong> </div>

 <div class='text-center align-self-center'> <p> <a href={% url 'editProfile' %}> Edit Bio </a> </p>  
</div>  

</div>

<div  class='col-xs-7 col-sm-7 col-md-7 col-lg-7 d-flex justify-content-start'> You haven't posted any pics yet...  <a href={% url 'klooniFeed' %}> Click here to post one </a> </div>

</div>


<!-- end of condition 'no posts yet'-->


    {% endif %}


</div>
</div>
{% endblock %}

klooni/templates/klooni_pages/search.html
{% extends 'klooni_pages/base.html'%}
{% load bootstrap4 %}


{% block content %}

<!-- Homepage replica -->

<div class='container'>
    {% include 'navbar.html' %}
<hr>



<!-- search results -->


  <div class="row searchResults">
    {% if searched_users %}
      <h2>Found {{ searched_users|length }} image(s) posted by {{message}}</h2>
    {% else %}
      <h2> Found 0 images or users  {{message}}</h2>
    {% endif %}

  </div>


<!-- end of search results -->


<div class='row justify-content-center top-buffer'>
{% for photo in photos %}

<div class='col-xs-7 col-sm-7 col-md-7 col-lg-7 d-block top-buffer'> 


<div class='d-inline-flex'>
<div class="userAvatar mr-2"> <img class='img-thumbnail' src="{{photo.user.prof_pic.cdn_url}}" alt='userAvatar'></div>

<div class='text-center align-self-center'> <strong> {{ photo.user.user.username}} </strong> </div>
</div>


<div class='d-flex justify-content-center'>
<img class='img-responsive imagePost' src="{{photo.image.cdn_url}}" alt='image'>
</div>

<p> {{photo.name}} </p>
<p> {{ photo.caption }} </p>
<p>
{{ photo.like_set.all|length }} <i class="fa fa-heart-o"> </i> {{ photo.comment_set.all|length }} <i class="fa fa-commenting-o"></i> </p>
<hr>


<hr>
</div>
{% endfor %}

</div>
</div>

{% endblock %}

klooni/templates/klooni_pages/update_profile.html
{% extends 'klooni_pages/base.html'%}
{% load bootstrap4 %}

{% block content %}


<div class='container'>
    {% include 'navbar.html' %}
<hr>
<div class='jumbotron'>


<div>

<!-- UPDATE USER PROFILE FORM-->
    <form enctype='multipart/form' action="{% url 'editProfile' %}" method="post">

    {% csrf_token %}

    {% bootstrap_form updateForm layout='inline' %}

    <div class="form-group">

    <input type="submit" class="btn btn-primary btn-sm my-2" value="Edit Profile">
    </div>
   </form>


</div>
</div>

{% endblock %}

klooni/templates/klooni_pages/upload_pic.html
{% extends 'klooni_pages/base.html'%}
{% load bootstrap4 %}

{% block content %}


<div class='container'>
    {% include 'navbar.html' %}
<hr>
<div class='jumbotron'>


<div>


<!-- UPLOAD IMAGES/FEED/VIDS FORM -->
    <form  action="{% url 'klooniFeed' %}" method="post">

    {% csrf_token %}

    {% bootstrap_form uploadForm layout='inline' %}

    <div class="form-group">

    <input type="submit" class="btn btn-primary btn-sm my-2" value="Upload">
    </div>
   </form>
</div>



</div>
</div>

{% endblock %}